### ISSUE TITLE
boids_bruteforce_dependency_graph Segfault 

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#555]
`boids_bruteforce_dependency_graph` is currently segfautling under linux, CUDA 11.3, gcc 10. `flamegpu::DependencyGraph::checkForUnattachedFunctions()`

```
0x0000555555597aba in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<AgentData> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<AgentData> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_begin (this=0x18) at /usr/include/c++/10/bits/hashtable.h:421
421           { return static_cast<__node_type*>(_M_before_begin._M_nxt); }
(cuda-gdb) backtrace
#0  0x0000555555597aba in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<AgentData> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<AgentData> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_begin (this=0x18) at /usr/include/c++/10/bits/hashtable.h:421
#1  0x00005555555963c1 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<AgentData> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<AgentData> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::begin (this=0x18) at /usr/include/c++/10/bits/hashtable.h:547
#2  0x0000555555594a38 in std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<AgentData>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<AgentData> > > >::begin (this=0x18)
    at /usr/include/c++/10/bits/unordered_map.h:334
#3  0x00005555555ec80c in DependencyGraph::checkForUnattachedFunctions (this=0x7fffffffbbf0)
    at /home/ptheywood/code/flamegpu/FLAMEGPU2-dupe/src/flamegpu/model/DependencyGraph.cpp:250
#4  0x00005555555eb4e4 in DependencyGraph::generateLayers (this=0x7fffffffbbf0, _model=...)
    at /home/ptheywood/code/flamegpu/FLAMEGPU2-dupe/src/flamegpu/model/DependencyGraph.cpp:85
#5  0x000055555557ea16 in main (argc=1, argv=0x7fffffffd3e8) at /home/ptheywood/code/flamegpu/FLAMEGPU2-dupe/examples/boids_bruteforce_dependency_graph/src/main.cu:320
```

**Comment by Robadob** [comment]
Why are both constructors even required? @MILeach 

Good find though.
